### ISSUE TITLE
BTM and Oracle XA database links

### ISSUE THREAD

**Issue by krokodylowy** [bitronix/btm#47]
Hi 
We got app based on Oracle+BTM+SpringFramerwotk+Hibernate
and I see resource leak if XA transaction contain operation on database links.
Resurces are released on application kill.

I know. this is common problem http://stackoverflow.com/questions/5088934/how-can-i-close-oracle-dblinks-in-jdbc-with-xa-datasources-and-transactions-to-a
but how to add additional action 'alter session close database link ' after transaction commit /rollback

**Comment by lorban** [comment]
You could register a synchronization (http://docs.oracle.com/javaee/5/api/javax/transaction/Synchronization.html) in the current transaction that would execute the alter session query.

Now the way to get the current transaction in which you can register the synchronization and a jdbc connection to run the query highly depends on your spring/hibernate stack.
