### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by maxant** [bitronix/btm#51]
Hi, firstly thank you for such a great little transaction manager. I have used it many times.  However since Codehaus was shutdown, the documentation that exists here is not as good as it was (e.g. http://docs.codehaus.org/display/BTM/Tomcat). Specifically, there is no information on how to integrate BTM with Tomcat and Jetty.

If need by, I would be happy to help by creating a pull request, but I'd need the original documentation to start with.

Thanks,
Ant

PS What I can find:

http://bitronix-transaction-manager.10986.n7.nabble.com/Bitronix-on-Ubuntu-server-V12-w-Tomcat7-issue-td1612.html

http://documentation.bonitasoft.com/ubuntu-openjdk-tomcat-mysql

http://bitronix-transaction-manager.10986.n7.nabble.com/tomcat-7-0-26-and-bitronix-td1155.html

**Comment by lorban** [comment]
Unfortunately, the original doc disappeared with Codehaus' decommissioning. IMHO it was a mistake to only rely on a wiki for the documentation, something like asciidoc (or whatever equivalent there was back in the days, if any) should have been used.

Fortunately, there is the wayback machine archive: http://web.archive.org/web/20150520175205/https://docs.codehaus.org/display/BTM/Tomcat2x

If you feel like rewriting the original doc as asciidoc, your pull requests would be welcome.

**Comment by maxant** [comment]
OK, I will send it soon...

**Comment by maxant** [comment]
Done. See https://github.com/bitronix/btm/pull/54 - let me know if it's ok?
