### ISSUE TITLE
Commit Markable Resource with Bitronix?

### ISSUE THREAD

**Issue by romming** [bitronix/btm#56]
Hi,

I'm using Bitronix with an LRC resource, and I have the following issue, which I believe is an instance of a known failure case with the LRC technique: Commit is called on the transaction, and the non-XA resource takes a while (~30 seconds) to complete the commit. During this window the system shuts down. After system restart the recoverer doesn't commit the XA resource (because it didn't register the non-XA commit completing). As a result, the non-XA resource is committed and the XA resource is not.

Any advice on how to get around this failure case? I can't do much about the long commit time for the non-XA resource. One technique I believe would solve the problem is the Commit Markable Resource technique described [here](https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.3/html/Development_Guide/sect-About_the_LRCO_Optimization_for_Single-phase_Commit_1PC.html). Is that supported by Bitronix, and if not, how hard would it be to extend Bitronix to do it (I'd consider contributing if it's feasible)? Any pointers would be greatly appreciated.

Thanks!

Christian

**Comment by lorban** [comment]
Hi,

The problem you describe is the well-known weakness of LRC, so there is nothing LRC can do to help you there.

The only alternative available as of now is to quit using LRC and only use proper XA resources but I suppose that's not an alternative in your case.

What JBoss calls "Commit Markable Resource", Weblogic calls it "Logging Last Resource". Implementing that in BTM wouldn't be trivial as that would require modifying some core implementation details (like making the journal not a global resource but a transaction-specific one) but that shouldn't be a hell of a job either.

I'm not worried about the technical side of adding such feature but more about the legal one: Oracle holds a patent on such technique, which has been the #1 reason why I never implemented some XA logging improvements like this one.
