### ISSUE TITLE
How to get native connection from PoolingDataSource of Bitronix

### ISSUE THREAD

**Issue by viswakalva** [bitronix/btm#76]
How to get the native connection (Native oracle connection in my case) from bitronix poolingdatasource inside spring @Transactional Method

**Comment by lorban** [comment]
```
Connection nativeConnection = connectionFromBtmPool.unwrap(java.sql.Connection.class);
```
See: https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html

**Comment by viswakalva** [comment]
Thanks for the reply @lorban the issue is I was able to get the native connection by unwrap  method, but distributed transaction seems not working fine.  below is the example 
class TestTrans{
@Autowired
DataSource btmPoolDatasource;
@Transactional(value = "platformTransactionManager", propagation = Propagation.REQUIRED)
public void methodTrans(){
Connection connection = btmPoolDatasource.getConnection();
Connection nativeConnection = connection.unwrap(java.sql.Connection.class);
    		//1. write to database using this nativeConnection creating prepared statement
               //2. some business logic. (when exception is thrown at this point the record which was saved in              //the DB is not rolled back.		
}
}

I am not sure do we need to manually comit or close the connection
