### ISSUE TITLE
How to rollback the transaction when in loop

### ISSUE THREAD

**Issue by testeradam** [bitronix/btm#82]
I am using BTM as Distributed transaction.Below is the use case where I couldn't figure out the best way.
Use Case: After reading a message from message broker my transaction starts and I call a Stored Procedure twice in the loop within the transaction. where the stored procedure responds just with success or failure. in the loop 1st time the Stored Procedure returns success and the second time the stored procedure returns failure. my business scenario is if stored procedure returns failure I need to send a message to JMS queue. I was able to send the message successfully. BUT the issue is my 1st stored procedure call records are stored in DB table because there was no exception for btm to roll back. In BTM perspective there was no exception, so btm initiates commit at the end. 
Required: the transaction should not commit but still, I need to send the message to jms queue within the same transaction.

**Comment by lorban** [comment]
> Required: the transaction should not commit but still, I need to send the message to jms queue within the same transaction.

That doesn't make sense: rolling back a transaction discards all sent JMS message by definition.

You have to rework your logic in a way that either the transaction should commit or you need to send the message from another transaction / non-transactionally.
