### ISSUE TITLE
Database Rollback in one scenario

### ISSUE THREAD

**Issue by testeradam** [bitronix/btm#83]
I am using btm as the Global transaction manager, I have one scenario where I have to rollback the database operation explicitly using rollback() method. when I do that it's erroring out saying can't rollback a resource enlisted in a global transaction. this is logical and I accept that. But is there any way I could get database connection alone which is enlisted in a global transaction to rollback? I have got the database connection using Connection conn = DataSourceUtils.getConnection(myDataSource);

**Comment by lorban** [comment]
> is there any way I could get database connection alone which is enlisted in a global transaction to rollback?

By definition, no. And by implementation too: once the DB and its JDBC driver have given up control of a transaction's lifecycle, there's no way back. And even if you could, you'd just potentially mess up the transaction's atomicity.

You have no choice but to rework your logic.
