### ISSUE TITLE
Question on rollback

### ISSUE THREAD

**Issue by testeradam** [bitronix/btm#87]
I am not sure if it's possible, Is there any way in bitronix distributed transaction for one Specific exception I can commit JMS Transaction alone and roll back the DB transaction.

**Comment by lorban** [comment]
What you're asking is nonsensical: a transaction must always be atomic by definition, which means everything has to either commit or rollback. Anything else would break the 'A' part of the ACID contract.

BTM like every other transaction manager on the planet will do everything it can to make what you're asking impossible, per the very own design of the specification it implements.
