### ISSUE TITLE
Using ActiveMQ and bitronix-transaction-manager redelivery issue

### ISSUE THREAD

**Issue by grahamryan25** [bitronix/btm#91]
Hello, I'm trying to test bitronix-transaction-manager with activemq. I'm running into this problem in my test cases. It would be great if anyone can help. 
When the JMS listener fails to process the message with an exception, the transaction gets rolled back, but  It's not following the redelivery policy I defined to redeliver three times on exception with delay of 5 seconds for each retry .
This is the configuration.
resource.mq1.className=org.apache.activemq.ActiveMQXAConnectionFactory
resource.mq1.uniqueName=jms/connectionFactory
resource.mq1.minPoolSize=0
resource.mq1.maxPoolSize=10
resource.mq1.driverProperties.brokerURL=tcp://localhost:61616
resource.mq1.driverProperties.redeliveryPolicy.initialRedeliveryDelay=0
resource.mq1.driverProperties.redeliveryPolicy.redeliveryDelay=5000
resource.mq1.driverProperties.redeliveryPolicy.maximumRedeliveries=3
resource.mq1.shareTransactionConnections=false
resource.mq1.automaticEnlistingEnabled=true
resource.mq1.allowLocalTransactions=true
resource.mq1.applyTransactionTimeout=true

**Comment by lorban** [comment]
Well, looking at your description of the problem, that doesn't look like a transaction manager's issue, but rather a MQ one.

I'd suggest you to investigate deeper to get a better idea of what's going on, and eventually be able to point your finger exactly where the problem is.
